# Site settings
name: Shuyang Dai's Blog
email: daishuyangchn@gmail.com
author: Shuyang Dai
url: https://daishuyangchn.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/daishuyangchn
baseurl: ""
description: Nothing is impossible to a willing heart! 人贵有志，学贵有恒。
meta_description: 戴舒扬;个人博客;
motto: Nothing is impossible to a willing heart.
banner: 人贵有志，学贵有恒。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: daishuyangchn

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

